name: 'Build and deploy HMS'

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    backend:
        runs-on: ubuntu-latest
        env:
            dotnet-version: '8.0'
        steps:
          - name: 'Checkout'
            uses: actions/checkout@v3
      
          - name: 'Setup .NET SDK ${{ env.dotnet-version }}'
            uses: actions/setup-dotnet@v2
            with:
              dotnet-version: ${{ env.dotnet-version }}
      
          - name: 'Restore dependencies'
            run: dotnet restore
            working-directory: ./Backend
            
          - name: 'Build'
            run: dotnet build --configuration Release
            working-directory: ./Backend
      