name: 'Build and deploy HMS'

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    azure:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
          - name: 'Checkout'
            uses: actions/checkout@v4

          - name: 'Login'
            uses: azure/login@v1
            with:
                client-id: 'a75e0ea3-3b64-4323-b205-f00ac0c101c6'
                tenant-id: '022e4faf-c745-475a-be06-06b1e1c9e39d'
                subscription-id: 'b33f0285-db27-4896-ac5c-df22004b0aba'

          - name: 'Deploy Azure Resources'
            working-directory: ./DevOps
            run: |
                az deployment group create \
                --resource-group hms \
                --name Deployment-dev-$(date +"%Y-%m-%dT%H-%M-%S") \
                --template-file infrastructure.bicep \
                --parameters \
                    location=westeurope \
                    env=dev

    backend:
        runs-on: ubuntu-latest
        needs:
            - azure
        env:
            dotnet-version: '8.0'
        steps:
          - name: 'Checkout'
            uses: actions/checkout@v4
      
          - name: 'Setup .NET SDK ${{ env.dotnet-version }}'
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: ${{ env.dotnet-version }}
      
          - name: 'Restore dependencies'
            run: dotnet restore
            working-directory: ./Backend
            
          - name: 'Build'
            run: dotnet build --configuration Release
            working-directory: ./Backend
      